#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Deploys the Contoso Healthcare Patient Portal infrastructure to Azure.

.DESCRIPTION
    This script orchestrates the deployment of all Azure resources required for the
    HIPAA-compliant patient portal including networking, compute, database, security,
    and monitoring components.

.PARAMETER Location
    Azure region for deployment (default: eastus2)

.PARAMETER Environment
    Environment name: dev, staging, or prod (default: prod)

.PARAMETER SqlAdminPassword
    SQL Server administrator password (if not provided, will prompt)

.PARAMETER WhatIf
    Runs deployment validation without creating resources

.PARAMETER SkipValidation
    Skips pre-deployment validation checks

.PARAMETER Force
    Bypasses interactive confirmation prompt (use with caution)

.EXAMPLE
    .\deploy.ps1 -Environment prod -Location eastus2

.EXAMPLE
    .\deploy.ps1 -WhatIf

.EXAMPLE
    .\deploy.ps1 -Environment dev -SqlAdminPassword 'SecureP@ssw0rd123!'

.NOTES
    Author: Generated by GitHub Copilot with bicep-implement agent
    Version: 1.0.0
    Date: 2025-11-18
    Requirements:
    - Azure CLI (az) version 2.50.0 or higher
    - Bicep CLI version 0.20.0 or higher
    - PowerShell 7.0 or higher
    - Azure subscription with Contributor access
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter()]
    [ValidateSet('swedencentral', 'eastus', 'eastus2', 'westus2', 'westeurope', 'northeurope')]
    [string]$Location = 'swedencentral',

    [Parameter()]
    [ValidateSet('dev', 'staging', 'prod')]
    [string]$Environment = 'prod',

    [Parameter()]
    [SecureString]$SqlAdminPassword,

    [Parameter()]
    [switch]$SkipValidation,

    [Parameter()]
    [switch]$Force
)

#Requires -Version 7.0

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ============================================================================
# CONFIGURATION
# ============================================================================

$ProjectName = 'contoso-patient-portal'
$DeploymentName = "$ProjectName-$Environment-$(Get-Date -Format 'yyyyMMdd-HHmmss')"
$TemplateFile = Join-Path $PSScriptRoot 'main.bicep'
$ParametersFile = Join-Path $PSScriptRoot 'main.bicepparam'

# ============================================================================
# FUNCTIONS
# ============================================================================

function Write-Header {
    param([string]$Message)
    Write-Host "`n" -NoNewline
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host " $Message" -ForegroundColor White
    Write-Host "============================================================================" -ForegroundColor Cyan
}

function Write-Info {
    param([string]$Message)
    Write-Host "ℹ️  " -NoNewline -ForegroundColor Blue
    Write-Host $Message -ForegroundColor Gray
}

function Write-Success {
    param([string]$Message)
    Write-Host "✅ " -NoNewline -ForegroundColor Green
    Write-Host $Message -ForegroundColor Green
}

function Write-Warning {
    param([string]$Message)
    Write-Host "⚠️  " -NoNewline -ForegroundColor Yellow
    Write-Host $Message -ForegroundColor Yellow
}

function Write-ErrorMessage {
    param([string]$Message)
    Write-Host "❌ " -NoNewline -ForegroundColor Red
    Write-Host $Message -ForegroundColor Red
}

function Test-Prerequisites {
    Write-Header "Checking Prerequisites"
    
    # Check Azure CLI
    Write-Info "Checking Azure CLI..."
    $azVersion = az version --output json 2>$null | ConvertFrom-Json
    if (-not $azVersion) {
        Write-ErrorMessage "Azure CLI is not installed. Please install from: https://aka.ms/azure-cli"
        return $false
    }
    Write-Success "Azure CLI version: $($azVersion.'azure-cli')"
    
    # Check Bicep CLI
    Write-Info "Checking Bicep CLI..."
    $bicepVersion = az bicep version 2>$null
    if (-not $bicepVersion) {
        Write-Warning "Bicep CLI not found. Installing..."
        az bicep install
        $bicepVersion = az bicep version
    }
    Write-Success "Bicep version: $bicepVersion"
    
    # Check Azure login
    Write-Info "Checking Azure authentication..."
    $account = az account show --output json 2>$null | ConvertFrom-Json
    if (-not $account) {
        Write-ErrorMessage "Not logged in to Azure. Please run: az login"
        return $false
    }
    Write-Success "Logged in as: $($account.user.name)"
    Write-Info "Subscription: $($account.name) ($($account.id))"
    
    # Get User Details for Entra ID Auth
    try {
        $global:currentUserObjectId = az ad signed-in-user show --query id -o tsv 2>$null
        $global:currentUserPrincipalName = az ad signed-in-user show --query userPrincipalName -o tsv 2>$null
        $global:currentUserType = az ad signed-in-user show --query type -o tsv 2>$null
        
        if ($global:currentUserObjectId) {
            Write-Info "Will configure SQL Server with Entra ID Admin: $global:currentUserPrincipalName"
        }
    }
    catch {
        Write-Warning "Could not retrieve signed-in user details for Entra ID auth. SQL Server will use SQL Auth only."
    }
    
    return $true
}

function Get-SqlPassword {
    if ($SqlAdminPassword) {
        return $SqlAdminPassword
    }
    
    Write-Host "`n" -NoNewline
    Write-Host "SQL Server Administrator Password" -ForegroundColor Yellow
    Write-Host "Requirements: 8+ characters, uppercase, lowercase, number, special char" -ForegroundColor Gray
    
    do {
        $password = Read-Host "Enter SQL admin password" -AsSecureString
        $confirmPassword = Read-Host "Confirm password" -AsSecureString
        
        $passwordText = [System.Net.NetworkCredential]::new('', $password).Password
        
        if ($passwordText.Length -lt 8) {
            Write-Warning "Password must be at least 8 characters"
            continue
        }
        
        # Relaxed complexity check to avoid issues with special characters
        if ($passwordText -cnotmatch '[A-Z]' -or $passwordText -cnotmatch '[a-z]' -or 
            $passwordText -notmatch '\d') {
            Write-Warning "Password must contain uppercase, lowercase, and number"
            continue
        }
        
        $confirmText = [System.Net.NetworkCredential]::new('', $confirmPassword).Password
        
        if ($passwordText -ne $confirmText) {
            Write-Warning "Passwords do not match"
            continue
        }
        
        Write-Success "Password validated"
        return $password
        
    } while ($true)
}

function Invoke-BicepValidation {
    Write-Header "Validating Bicep Templates"
    
    # Bicep build
    Write-Info "Building Bicep template..."
    $buildResult = az bicep build --file $TemplateFile --stdout 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-ErrorMessage "Bicep build failed:"
        Write-Host $buildResult -ForegroundColor Red
        return $false
    }
    Write-Success "Bicep build successful"
    
    # Bicep lint
    Write-Info "Linting Bicep template..."
    $lintResult = bicep lint $TemplateFile 2>&1
    $lintExitCode = $LASTEXITCODE
    
    if ($lintResult -match 'Error') {
        Write-ErrorMessage "Bicep lint found errors:"
        Write-Host $lintResult -ForegroundColor Red
        return $false
    }
    if ($lintResult -match 'Warning') {
        Write-Warning "Bicep lint found warnings (non-blocking):"
        Write-Host $lintResult -ForegroundColor Yellow
        # Warnings are non-blocking, continue with deployment
    }
    else {
        Write-Success "Bicep lint passed"
    }
    
    return $true
}

function Invoke-Deployment {
    param(
        [SecureString]$Password,
        [bool]$DryRun
    )
    
    Write-Header "Deploying Infrastructure"
    
    Write-Info "Deployment Name: $DeploymentName"
    Write-Info "Location: $Location"
    Write-Info "Environment: $Environment"
    Write-Info "Project: $ProjectName"
    
    if ($DryRun) {
        Write-Warning "Running in WHAT-IF mode - no resources will be created"
    }
    
    # Convert SecureString to plain text for Azure CLI
    $passwordText = [System.Net.NetworkCredential]::new('', $Password).Password
    
    # Build deployment command
    $deployCmd = @(
        'deployment', 'sub', 'create'
        '--name', $DeploymentName
        '--location', $Location
        '--template-file', $TemplateFile
        '--parameters', "location=$Location"
        '--parameters', "environment=$Environment"
        '--parameters', "projectName=$ProjectName"
        '--parameters', "sqlAdminPassword=$passwordText"
    )

    if ($global:currentUserObjectId) {
        $deployCmd += '--parameters'
        $deployCmd += "azureAdAdminObjectId=$global:currentUserObjectId"
        $deployCmd += '--parameters'
        $deployCmd += "azureAdAdminLogin=$global:currentUserPrincipalName"
        # Assuming 'User' type for signed-in user, but could be ServicePrincipal
        # $deployCmd += '--parameters'
        # $deployCmd += "azureAdAdminType=User" 
    }
    
    if ($DryRun) {
        $deployCmd += '--what-if'
    }
    
    # Execute deployment
    Write-Host "`n"
    & az @deployCmd
    
    if ($LASTEXITCODE -ne 0) {
        Write-ErrorMessage "Deployment failed!"
        return $false
    }
    
    if (-not $DryRun) {
        Write-Success "Deployment completed successfully!"
    }
    
    return $true
}

function Show-DeploymentOutputs {
    Write-Header "Deployment Outputs"
    
    $outputs = az deployment sub show `
        --name $DeploymentName `
        --query 'properties.outputs' `
        --output json | ConvertFrom-Json
    
    if ($outputs) {
        Write-Host "Resource Group: " -NoNewline -ForegroundColor Cyan
        Write-Host $outputs.resourceGroupName.value -ForegroundColor White
        
        Write-Host "App Service URL: " -NoNewline -ForegroundColor Cyan
        Write-Host $outputs.appServiceUrl.value -ForegroundColor White
        
        Write-Host "SQL Server FQDN: " -NoNewline -ForegroundColor Cyan
        Write-Host $outputs.sqlServerFqdn.value -ForegroundColor White
        
        Write-Host "Key Vault URI: " -NoNewline -ForegroundColor Cyan
        Write-Host $outputs.keyVaultUri.value -ForegroundColor White
    }
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

try {
    Write-Header "Contoso Healthcare Patient Portal - Infrastructure Deployment"
    Write-Host "Environment: $Environment | Location: $Location" -ForegroundColor Gray
    Write-Host "Timestamp: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -ForegroundColor Gray
    
    # Check prerequisites
    if (-not $SkipValidation) {
        if (-not (Test-Prerequisites)) {
            exit 1
        }
    }
    
    # Get SQL password
    $sqlPassword = Get-SqlPassword
    
    # Validate Bicep templates
    if (-not $SkipValidation) {
        if (-not (Invoke-BicepValidation)) {
            exit 1
        }
    }
    
    # Confirm deployment
    if (-not $WhatIfPreference -and -not $Force -and $PSCmdlet.ShouldProcess("Azure Subscription", "Deploy Infrastructure")) {
        Write-Host "`n"
        Write-Warning "This will deploy resources to your Azure subscription."
        Write-Warning "Estimated monthly cost: `$331-346"
        $confirm = Read-Host "Continue? (yes/no)"
        
        if ($confirm -ne 'yes') {
            Write-Info "Deployment cancelled by user"
            exit 0
        }
    }

    # Execute deployment
    if (-not (Invoke-Deployment -Password $sqlPassword -DryRun:$WhatIfPreference)) {
        exit 1
    }
    
    # Show outputs (skip for what-if)
    if (-not $WhatIfPreference) {
        Show-DeploymentOutputs
        
        Write-Header "Next Steps"
        Write-Info "1. Configure App Service deployment settings"
        Write-Info "2. Deploy application code to App Service"
        Write-Info "3. Configure database schema and seed data"
        Write-Info "4. Set up monitoring alerts in Application Insights"
        Write-Info "5. Review Azure Policy compliance in Security Center"
    }
    
    Write-Host "`n"
    Write-Success "Deployment script completed successfully!"
    
}
catch {
    Write-ErrorMessage "Deployment failed with error:"
    Write-Host $_.Exception.Message -ForegroundColor Red
    Write-Host $_.ScriptStackTrace -ForegroundColor Gray
    exit 1
}
