// ============================================================================
// Main Bicep Template - Contoso Healthcare Patient Portal
// ============================================================================
// Purpose: Orchestrates deployment of HIPAA-compliant patient portal infrastructure
// Author: Generated by GitHub Copilot with bicep-implement agent
// Date: 2025-11-18

targetScope = 'subscription'

// ============================================================================
// PARAMETERS
// ============================================================================

@description('Azure region for all resources')
@allowed([
  'swedencentral'
  'germanywestcentral'
  'westeurope'
  'northeurope'
])
param location string = 'swedencentral'

@description('Environment name (dev, staging, prod)')
@allowed([
  'dev'
  'staging'
  'prod'
])
param environment string = 'prod'

@description('Project name used for resource naming')
param projectName string = 'contoso-patient-portal'

@description('SQL Server administrator username')
param sqlAdminUsername string = 'sqladmin'

@description('SQL Server administrator password')
@secure()
param sqlAdminPassword string

@description('Azure AD administrator object ID for SQL Server')
param azureAdAdminObjectId string = ''

@description('Azure AD administrator login name for SQL Server')
param azureAdAdminLogin string = ''

@description('Resource tags for governance')
param tags object = {
  Environment: environment
  ManagedBy: 'Bicep'
  Project: 'PatientPortal'
  CostCenter: 'Healthcare-IT'
  Compliance: 'HIPAA'
  SecurityControl: 'Ignore' // Bypass Azure Policy for demo/dev environment
}

// ============================================================================
// VARIABLES
// ============================================================================

// Generate unique suffix for resource names (5-6 characters from resource group ID)
var uniqueSuffix = uniqueString(subscription().subscriptionId, resourceGroupName)

var resourceGroupName = 'rg-${projectName}-${environment}'
var deploymentNamePrefix = '${projectName}-${environment}'

// ============================================================================
// RESOURCE GROUP
// ============================================================================

resource resourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' = {
  name: resourceGroupName
  location: location
  tags: tags
}

// ============================================================================
// PHASE 1: FOUNDATION & NETWORKING
// ============================================================================

module networking 'modules/networking.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-networking'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
  }
}

// ============================================================================
// PHASE 2: PLATFORM SERVICES
// ============================================================================

module monitoring 'modules/monitoring.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-monitoring'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
  }
}

module appServicePlan 'modules/app-service-plan.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-asp'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
  }
}

module sqlServer 'modules/sql-server.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-sqlserver'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    sqlAdminUsername: sqlAdminUsername
    sqlAdminPassword: sqlAdminPassword
    azureAdAdminObjectId: azureAdAdminObjectId
    azureAdAdminLogin: azureAdAdminLogin
    azureAdAdminType: 'User'
    tags: tags
  }
}

module keyVault 'modules/key-vault.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-keyvault'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    tags: tags
  }
}

// ============================================================================
// PHASE 3: SECURITY & APPLICATION DEPLOYMENT
// ============================================================================

module sqlDatabase 'modules/sql-database.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-sqldb'
  params: {
    location: location
    environment: environment
    uniqueSuffix: uniqueSuffix
    sqlServerName: sqlServer.outputs.sqlServerName
    tags: tags
  }
}

module privateEndpoints 'modules/private-endpoints.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-private-endpoints'
  params: {
    location: location
    environment: environment
    uniqueSuffix: uniqueSuffix
    keyVaultId: keyVault.outputs.keyVaultId
    sqlServerId: sqlServer.outputs.sqlServerId
    privateEndpointSubnetId: networking.outputs.privateEndpointSubnetId
    tags: tags
  }
}

module appService 'modules/app-service.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-appservice'
  params: {
    location: location
    environment: environment
    projectName: projectName
    uniqueSuffix: uniqueSuffix
    appServicePlanId: appServicePlan.outputs.appServicePlanId
    webSubnetId: networking.outputs.webSubnetId
    applicationInsightsConnectionString: monitoring.outputs.applicationInsightsConnectionString
    tags: tags
  }
}

// ============================================================================
// PHASE 4: CONFIGURATION & ACCESS MANAGEMENT
// ============================================================================

module keyVaultSecrets 'modules/key-vault-secrets.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-kv-secrets'
  params: {
    keyVaultName: keyVault.outputs.keyVaultName
    sqlConnectionString: 'Server=tcp:${sqlServer.outputs.fullyQualifiedDomainName},1433;Initial Catalog=${sqlDatabase.outputs.databaseName};Authentication=Active Directory Managed Identity;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
    applicationInsightsConnectionString: monitoring.outputs.applicationInsightsConnectionString
  }
}

module rbacAssignments 'modules/rbac-assignments.bicep' = {
  scope: resourceGroup
  name: '${deploymentNamePrefix}-rbac'
  params: {
    keyVaultName: keyVault.outputs.keyVaultName
    appServicePrincipalId: appService.outputs.appServicePrincipalId
  }
}

// ============================================================================
// OUTPUTS
// ============================================================================

@description('Resource Group name')
output resourceGroupName string = resourceGroup.name

@description('App Service default hostname')
output appServiceUrl string = 'https://${appService.outputs.defaultHostName}'

@description('SQL Server fully qualified domain name')
output sqlServerFqdn string = sqlServer.outputs.fullyQualifiedDomainName

@description('Key Vault URI')
output keyVaultUri string = keyVault.outputs.keyVaultUri

@description('Application Insights connection string')
@secure()
output applicationInsightsConnectionString string = monitoring.outputs.applicationInsightsConnectionString

@description('App Service Managed Identity Principal ID')
output appServicePrincipalId string = appService.outputs.appServicePrincipalId
